### ISSUE TITLE
XO cannot handle generic methods

### ISSUE THREAD

**Issue by obfischer** [buschmais/extended-objects#165]
While writing a plugin for jQAssistant to scan JSON files I got problems with generic methods inherited from a common base interface. I have to following interfaces:

    @Abstract
    public interface JSONValueDescriptor<V> extends JSONDescriptor {
        void setValue(V value);
        V getValue();
    }

    public interface JSONArrayValueDescriptor 
         extends JSONValueDescriptor<JSONArrayDescriptor> {
        @Override
         void setValue(JSONArrayDescriptor value);
        @Override
        JSONArrayDescriptor getValue();
    }

    @Label("Value")
    public interface JSONObjectValueDescriptor 
         extends JSONValueDescriptor<JSONObjectDescriptor> {
        @Override
         void setValue(JSONObjectDescriptor value);
        @Override
        JSONObjectDescriptor getValue(); 
    }

When I try to add the `JSONArrayValueDescriptor` to another descriptor I get the following exception:

    java.lang.IllegalArgumentException: methods with same signature getValue() but incompatible 
    return types: [interface com.buschmais.jqassistant.plugin.json.api.model.JSONArrayDescriptor,
    interface com.buschmais.jqassistant.plugin.json.api.model.JSONObjectDescriptor]

How can I handle this? I am using XO 0.6.0-SNAPSHOT.

**Comment by DirkMahler** [comment]
The issues was caused by an ambgiuous mapping, i.e. a proxy was created from two interfaces declaring the same method but with different return types.
