### ISSUE TITLE
Filter results of getter methods in labeled types based on their return type

### ISSUE THREAD

**Issue by StephanPirnbaum** [buschmais/extended-objects#172]
Currently, getter methods with different return types in a labeled type are allowed to be annotated with the same relation name. However, the returned collection is not respecting the specified return type parameter.

Example:

    @Relation("CONTAINS")
    @Outgoing
    Set<Type1> getType1();

    @Relation("CONTAINS")
    @Outgoing
    Set<Type2> getType2();

Both methods will return a set with the same content. A ClassCastException will be thrown when the values of the returned set are used. The set should be filtered before it is returned to only contain instances of the specified class.

**Comment by DirkMahler** [comment]
The change has been applied for to-many and to-one relations. The behavior of the latter is still not perfect: at this time there can be only one physical relation at the same time, i.e. if a class A has two to-one relations to B and C of the same type then setting a B will  case returning null for getting the C relation and vice versa.
