### ISSUE TITLE
Safe usage of the XO Annotation Relation

### ISSUE THREAD

**Issue by obfischer** [buschmais/extended-objects#173]
If a user of XO annotates a setter with `@Relation`, the annotation is silently ignored and the name of the of relation is derived from the according getter. 

This might lead to problems for developers who are used the other frameworks, which allow the annotation of the setter as well as the annotation of the getter.

Therefore I would like to see one of the following solutions implemented:

1. XO should fail if it finds the `@Relation` annotation on a setter.
2. XO should allow to annotate the setters too.

**_Example_**

In the following example the name of the resulting relation is `VALUE` and not `HAS_VALUE` as intended by the developer.

```java
YMLDescriptor getValue();

@Relation("HAS_VALUE")
void setValue(YMLDescriptor descriptor);
```

**Comment by DirkMahler** [comment]
The behavior has been changed such that property related annotations are now only allowed on getters.

**Comment by obfischer** [comment]
Thank you.
