### ISSUE TITLE
XO returns wrong collection size for multiple collections annotated with the same relation

### ISSUE THREAD

**Issue by obfischer** [buschmais/extended-objects#174]
Given the following code fragment:

```java
@Relation("HAS_ITEM")
List<YMLSequenceDescriptor> getSequences();

@Relation("HAS_ITEM")
List<YMLMapDescriptor> getMaps();

@Relation("HAS_ITEM")
List<YMLScalarDescriptor> getScalars();
```

And assuming that any of the three collections contains three elements, then calling `.size()` on every collection returns 3.

IMHO the correct behaviour would be, that only the collection for sequences should return 3, while all other shoudl return only zero.

**Comment by DirkMahler** [comment]
Duplicates #172 

I'd like to treat this more as a feature than a bug: The model in the datastore is ambiguous, XO shall be able to compensate for that.
