### ISSUE TITLE
Query result within a transaction is flaky

### ISSUE THREAD

**Issue by f4lco** [buschmais/extended-objects#177]
> The definition of insanity is doing the same thing over and over again and expecting a different result.

I was going nuts for an entire day when prototyping a plugin for jQAssistant. I couldn't explain my observations, so I shrunk my code under test until... I came to the conclusion that XO cannot always agree which node labels to return. When packing the "hello world" type in a loop, I get back very different results:

```kotlin
import com.buschmais.jqassistant.plugin.common.api.model.*
import com.buschmais.xo.api.XOManagerFactory
import com.buschmais.xo.api.annotation.Abstract
import com.buschmais.xo.api.bootstrap.XO
import com.buschmais.xo.api.bootstrap.XOUnit
import com.buschmais.xo.neo4j.api.annotation.Label
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.DynamicTest
import org.junit.jupiter.api.TestFactory
import java.net.URI
import java.util.stream.Stream


@Abstract
@Label("Spam")
interface SpamDescriptor

interface SpamSourcesDirectoryDescriptor : DirectoryDescriptor, ArtifactDescriptor,
  SpamDescriptor

interface SpamSourceFileDescriptor : FileDescriptor, SpamDescriptor

class BugReproIT {

  @TestFactory
  fun create(): Stream<DynamicTest> {
    return (1..20).map {
      DynamicTest.dynamicTest("Attempt $it") {
        skipFlush()
      }
    }.stream()
  }

  fun skipFlush() {
    val unit = XOUnit.builder().apply {
      uri(URI("memory:///"))
      provider(Class.forName("com.buschmais.xo.neo4j.embedded.api.EmbeddedNeo4jXOProvider"))
      type(FileNameDescriptor::class.java)
      type(FileContainerDescriptor::class.java)
      type(FileDescriptor::class.java)
      type(DirectoryDescriptor::class.java)
      type(DependsOnDescriptor::class.java)
      type(SpamDescriptor::class.java)
      type(SpamSourcesDirectoryDescriptor::class.java)
      type(SpamSourceFileDescriptor::class.java)
    }.build()

    val managerFactory: XOManagerFactory = XO.createXOManagerFactory(unit)
    val manager = managerFactory.createXOManager()

    manager.currentTransaction().begin()
    manager.create(SpamSourcesDirectoryDescriptor::class.java)

    // flush
    // manager.currentTransaction().commit()
    // manager.currentTransaction().begin()
    // end flush

    val spam = manager.createQuery(
      """
      MATCH (n:Spam:File)
      RETURN n
    """, SpamSourcesDirectoryDescriptor::class.java
    ).execute().singleResult

    assertTrue(spam is SpamSourcesDirectoryDescriptor)
    assertTrue(spam !is SpamSourceFileDescriptor)

    manager.currentTransaction().commit()
    manager.close()
    managerFactory.close()
  }
}
```

* I think that the result is bound to have both descriptors.
* The two assertions in the test model the most frequent response from XO.
* The last assertion fails in a minority of instances. These are the instances when I deem the result actually correct.
* 20 repetitions almost always triggers this behavior. I routinely observe 20% to 25% of test failures per run, sometimes less.
* When starting a new transaction (see commented out code), the behavior seems to be  consistent, that is, consistently correct (the node has both labels / descriptors)

Screenshots for funsies:

| typical | once-in-a-lifetime |
|--------|-------------------|
| ![image](https://user-images.githubusercontent.com/29141485/113309576-93e14400-9307-11eb-917b-9e1762544a01.png) | ![image](https://user-images.githubusercontent.com/29141485/113309936-f6d2db00-9307-11eb-99c7-62657d01e496.png) |

(all failures have the same root cause, the same assertion failure, no other exception)

Setup:

- Mac OS Big Sur
- Java 11
- jQAssistant 1.9.1
- XO 1.1.0

Am I using XO's API correctly / is there any wrongdoing in the test code? Is there anything I can do for further analysis? Is there any point of reference (code-wise), which might explain the observed behavior? I'd be glad to hear from you, @DirkMahler.

**Comment by DirkMahler** [comment]
The behavior looks weird but explainable:

According to your definition SpamSourceFileDescriptor has the labels `:Spam:File:Artifact`, SpamSourcesDirectoryDescriptor has exactly the same labels but additionally `:Directory` (as the used DirectoryDescriptor itself is a FileDescriptor). So implicitly a SpamSourcesDirectoryDescriptor implements SpamSourceFileDescriptor as well.

And now the funny part starts: why is that sometimes visible, sometimes not? 

- If a query is executed the applicable types are determined by inspecting the labels attached to the returned node. This normally would result in both interfaces
- Due to an internal optimization `xoManager.create()` returns an instance of exactly the types that have been passed as parameter (i.e. SpamSourcesDirectoryDescriptor, but not SpamSourceFileDescriptor), the labels are not evaluated at this time
- The test succeeds/fails "sometimes" as the instance created by xoManager.create() is weakly referenced, i.e. the query might still see this or needs to recreate it according to the labels found on the node

So this behavior is caused by the combination of an ambiguous type definition paired with the optimization of `xoManager.create()`.

**Comment by f4lco** [comment]
Thank you so much @DirkMahler this answer is really spot on 💯 

Your thesis is confirmed ✅  
Indeed, after assigning a local variable I observe stable behavior just as you described.

I was afraid that my model definition might not be valid or expose ambiguity. How do you think this behavior is related to the "lack of discriminators" warning?
https://github.com/buschmais/extended-objects/blob/1824341b5db86d9eed1a009233493e5a3baa8c6d/impl/src/main/java/com/buschmais/xo/impl/metadata/EntityTypeMetadataResolver.java#L81-L89
Could one possibly add a validation to XO to forbid ambiguous declarations such as mine? Or do you think that such a warning would basically complain about all template types? Thanks again for your time + effort for the detailed explanation.

**Comment by f4lco** [comment]
It's been a while - closing this as I do not want to sit on top of your bug tracker with a wrong statement 😉 Thank you so much and keep up the good work.
